### PR TITLE
Moved LocaleHolder from Core/commons-app to Plugin-DevEnv.

### PR DESCRIPTION
**Pull request by skrchnavy**
To review this change used in UnifiedViews/Core feature/i18n branch.

### CODE REVIEW

**Comment by skrchnavy** [comment]
@eea02 to respond

**Comment by eea02** [comment]
LocaleHolder class is not used by localization system of DPU's. It is used to localize Core modules. I placed it in Plugin-DevEnv project because all Core modules depends on it.
The default value is there beacuse of defensive programming approach. I could have used Locale.getDefault(), but this could be more error-prone.

**Comment by skodape** [comment]
The 'issue' here is that the DevEnv should contains API for plugins not core. You are right that there is no common module under dataunits and commons-app. So we would need at two instances now (dataunits - as a service used by DataUnits, CommonsApp - backend, frontedn .. ).

Still I would strongly suggest not put this class here. As the removal of such class would require increase API version to 3.0.0 as removal break backward compatibility (or 4.0.0 if we use 3.0.0 during helpers merge).

**Comment by skrchnavy** [comment]
@eea02 - agreed to remove class as @skodape  proposed. This pull request (branch) will be deleted

**Pull request closed without merging**
