### PR TITLE
Support for metadata manipulation using DCAT Distribution model

### PR DESCRIPTION
**Pull request by mkl-eea-sk**
provides support for changes in:
https://github.com/OpenDataNode/UVPlugin-filesToCKAN/pull/8
https://github.com/UnifiedViews/Plugins/pull/236

### CODE REVIEW

**Comment by tomas-knap** [comment]
In "uv-dpu-helpers", there is a package eu.unifiedviews.helpers.dataunit.distribution where distribution classes are. This is a bit confusing - either we should move the package to uv-dataunit-helpers module (which is probably not possible due to reference to: eu.unifiedviews.helpers.dpu.rdf.EntityBuilder from DistributionToStatementsConverter) or rename the package to eu.unifiedviews.helpers.dpu.distribution. 

Please comment the public classes so that it is clear how they should be used by DPus and what they do - DistributionMerger, DistributionToResourceConvertor, DCAT, .. Now it may see obvious, but if we return back to it later, it may not.

**Comment by mkl-eea-sk** [comment]
Yup, EntityBuilder is in wrong place. Whole modularization of devenv is wrong :)

**Comment by skrchnavy** [comment]
Entity builder is in helper, so we can move the class into proper place. It affects only compilation of DPUs, that uses it. @tomas-knap is it OK?

**Comment by tomas-knap** [comment]
@skodape, Do some of the CUNI DPUs use eu.unifiedviews.helpers.dpu.rdf.EntityBuilder?

**Comment by tomas-knap** [comment]
EntityBuilder is used by certain CUNI DPUs - should be left where it is - it is not that important to move it around.

**Comment by skrchnavy** [comment]
@mkl-eea-sk what is status of this PR / branch?

**Comment by mkl-eea-sk** [comment]
Am I supposed to, additionally to creating pull request, mark it as ready for test or what am I supposed to do indicate it is done (at least my opinion)

**Comment by skrchnavy** [comment]
ready for test was enough.

**Comment by mkl-eea-sk** [comment]
closing and not merging for now, it would be nice to somehow retain the code however, if we will implement anything with dcat in future.

**Comment by skrchnavy** [comment]
branch deleted, can be restored

**Pull request closed without merging**
