### PR TITLE
Interface for Relational Data unit and helpers

### PR DESCRIPTION
**Pull request by skrchnavy**
Related to #8

### CODE REVIEW

**Comment by tomas-knap** [comment]
Ok, but please supplement "WritableRelationalDataUnit.updateExistingTableName()" code with the following comment:

The typical use for this method is when it is necessary to copy entry from input data unit to output data unit while retaining its symbolic name and all the metadata, but the target physical table has to be different from the source one - the data changed. To realize this, CopyHelper is used and then WritableRelationalDataUnit.updateExistingTableName() is called .

 An alternative to WritableRelationalDataUnit.updateExistingTableName(sn, dbTable) would be to call addExistingDbTable(sn, dbTable) and then use CopyHelper to copy all metadata except of the physical table name from input to output. But this approach has the problems that: current implementation of addExistingDbTable(sn, dbTable) will add second entry with the same symbolic name (which is not what is intended), and, further, the entry in the output data unit will have different ID to which metadata properties are attached, so simple CopyHelper is not enough, but cloning is needed. The alternative approach is possible future work.

**Comment by skrchnavy** [comment]
@eea03 add requested comment to interface

**Comment by eea03** [comment]
@tomas-knap just to clarify: should the second paragraph be also a part of the comment that should be supplemented or is it just an explaination for us?

**Comment by tomas-knap** [comment]
Yes, thanks!

**Comment by eea03** [comment]
Ok, done

**Pull request merged**
