### PR TITLE
DPU dialog context extended, changes in DPU execution context

### PR DESCRIPTION
**Pull request by eea03**
New methods added to DPU dialog context to provide information about logged user. This information is needed in design time of pipeline for some new DPUs retrieving data from CKAN catalog.
Method in DPU execution context interface renamed as actual name does not correspond to what the method really returns;

### CODE REVIEW

**Comment by eea03** [comment]
Implementation of the interfaces changes in Core is in https://github.com/UnifiedViews/Core/pull/388

**Comment by eea03** [comment]
Please, approve ASAP, these changes are needed for CKAN DPUs in order to make the UV - CKAN integration work. It would be much simpler if we had this in develop

**Comment by skrchnavy** [comment]
@tomas-knap please comment / approve

**Comment by tomas-knap** [comment]
Ok, but please align the names. Before this pull request, there was method "getPipelineOwner()" to get username of the pipeline owner. So the proposed methods should be renamed as follows to be consistent: 
1) getPipelineExecutorUserName() -> getPipelineExecutionOwner() 
2) getPipelineExecutorUserExternalId() ->  getPipelineExecutionOwnerExternalIdentifier()

**Pull request merged**
