### PR TITLE
Cryptography support in API and helpers

### PR DESCRIPTION
**Pull request by skrchnavy**
Based on #22

### CODE REVIEW

**Comment by skodape** [comment]
I would add an exception to the Cryptography interface, as those methods can fail. Currently RuntimeException is used, I'm not sure if it's the best option for user (user get read error).

Also +1 for existing comments, but -1 for missing comments on the main class :( like use conditions, what happen if this functionality is not accessible, suitability for encrypting larger strings?

Other comments together with: https://github.com/UnifiedViews/Core/pull/323

Small note: I don't like the eu.unifiedviews.helpers.util package for Vaadin. It's like you are creating a strand alone, package space.

**Comment by skrchnavy** [comment]
@skodape / @tomas-knap - what is proposed namespace?
@eea01 - comments have to be added when missing

**Comment by eea01** [comment]
The functionality was tested only on passwords, short strings.

**Comment by skodape** [comment]
As to a package I would suggest eu.unifiedviews.helpers.dpu.vaadin.components/util for the CryptograhpyField.
The idea is to keep Vaadin related stuff under Vaadin package (if possible). 

None: you may consider passing dialog-context (or UserDialogContext) to this element instead of just "cryptography" the idea is that in future you may wan't to add some common description/tool box, and then you will need localization there. It may then save some time updating all DPUs that are using this component.

As to the Crypthography class it self, I don't have better idea where to put it (package). It depends if you have plans for more of such features, otherwise I'm fine with the placement.

To the string length, I think it may be nice to add some comment. As some developer may try to use this for files or whole configurations - without specification I would expect it to work just fine, while it may have some limitations (like return string 10 times bigger, how much computational power it costs, etc .. )  - I do not know, just giving an opinion.

+ Also on second sight, like should I use getValue, setValue or getEcryptedValue - it looks like space for errors, because as a Vaadin "developer" I would use getValue and setValue as it's default API for all components - expecting that the password will be encrypted, but it will probably be not?
- Is there a reason why just don't override the get/setValue?

**Comment by tomas-knap** [comment]
See https://team.eea.sk/wiki/display/OD/Cryptography+support+for+DPUs

This pull request should NOT be merged. To implement cryptography, please finalize the branch https://github.com/UnifiedViews/Plugin-DevEnv/commits/feature/cryptographyHelper, which I sketched for you. The changes are described in https://team.eea.sk/wiki/display/OD/Cryptography+support+for+DPUs. All is implemented in two classes.

**Pull request closed without merging**
