### PR TITLE
Generation of About<_lang>.html from About<_lang>.md

### LINKED ISSUE #30: Support for generation of about page from markdown files in Plugins
To implement task or define a configuration for generation of about pages in Plugins.

### PR DESCRIPTION
**Pull request by skrchnavy**
Support to generate About.html using convertor from markdown to html (https://github.com/walokra/markdown-page-generator-plugin)

Connected to #41 
Resolves #30

### CODE REVIEW

**Comment by skrchnavy** [comment]
https://github.com/UnifiedViews/Plugin-DevEnv/blob/feature/about_tab_improvement_phase1/uv-dpu-helpers/src/main/java/eu/unifiedviews/helpers/dpu/vaadin/dialog/AboutTab.java#L68 shall be reworked to display only user specific information. Technical information (for example build number) shall be moved to another place or shall be visible in special mode of UV (development mode).

**Comment by tomas-knap** [comment]
Ok, layout of the HTML page can be improved, but this can be done later. 

Just two points; 
1) Build info should be moved e.g. to general tab with JAR path and replace button (as @skrchnavy also wrote)
2) I would suggest to remove "Powered by CUNI helpers":

screen shot 2015-07-20 at 12 21 48

**Comment by skrchnavy** [comment]
To simplify this, we shall in first step remove PoweredBy and put buildInfo into footer (if we need it).
Moving to DPU description tab requires more changes.

**Comment by tomas-knap** [comment]
Yes, put build info at least to footer. Remove PoweredBy CUNI. Otherwise OK.

**Comment by mkl-eea-sk** [comment]
Before https://github.com/UnifiedViews/Plugin-DevEnv/commit/95f1380dfbfbca3b6fe3ad7f13f23c84e5a1ca13 :
filesdownload_before

After:
filesdown_after

**Pull request merged**
